### ISSUE TITLE
想玩 Web Scraping? 用這個 repository 就對了。

### ISSUE THREAD

**Issue by telunyang** [JCEleanor/web-sraping-with-python#1]
專案連結↓
[telunyang/python_web_scraping](https://github.com/telunyang/python_web_scraping)
```pdf 不是重點，ipynb 才是精華所在，最後再嚐試 cases 裡面的範例；不定時更版。```

---

範例影片↓
[![封面](https://i.ytimg.com/vi/jJzZcMjZsKM/hqdefault.jpg)](https://www.youtube.com/watch?v=jJzZcMjZsKM "取得金庸小說的內容，並存成txt與json檔")

**Comment by JCEleanor** [comment]
> 專案連結↓
> [telunyang/python_web_scraping](https://github.com/telunyang/python_web_scraping)
> `pdf 不是重點，ipynb 才是精華所在，最後再嚐試 cases 裡面的範例；不定時更版。`
> 
> 範例影片↓
> [![封面](https://camo.githubusercontent.com/3132ec92e0b7a147b43a2ab0fbe45b0035cbd1f261e2973f55523c5aa7721ea4/68747470733a2f2f692e7974696d672e636f6d2f76692f6a4a7a5a634d6a5a734b4d2f687164656661756c742e6a7067)](https://www.youtube.com/watch?v=jJzZcMjZsKM)

好DER! 感謝老師！(*´▽`*)
